### ISSUE TITLE
Pathlib instead of os.path

### ISSUE THREAD

**Issue by klieret** [gnn-tracking/gnn_tracking#258]

**Comment by shubhanshu02** [comment]
Hi @klieret! I am interested in working on this issue. 

From what I understood, the repo seems to only have occurrences of the `join` function from  `os.path`. When using the `Pathlib`, we can directly use `/` to perform joins on the paths. So, all that needs to be done is that initialize the path with the Pathlib (Say `Path(in_dir)`) and then perform this instead of using `os.path.join`. Can you confirm if I am thinking in the right direction?

**Comment by klieret** [comment]
yes, it's pretty trivial, just porting to the more elegant pathlib style and cleaning up :)  The only thing to make sure is that `__init__`  and functions accept `os.PathLike | str` for convenience/backward compatibility

**Comment by shubhanshu02** [comment]
Got it. Let me try. Thanks.
